run:
  allow-parallel-runners: true
  timeout: 5m
  tests: false

linters:
  enable:
    - govet
    - staticcheck
    - revive
    - gofmt
    - goimports
    - errcheck
    - copyloopvar
  disable:
    - typecheck
