run:
  allow-parallel-runners: true
  timeout: 5m
  tests: false

linters:
  disable-all: true
  enable:
    - govet
    - staticcheck
    - revive
    - gofmt
    - goimports
    - errcheck
    - copyloopvar
