run:
  allow-parallel-runners: true
  timeout: 5m
  tests: false

linters:
  enable:
    - gofmt
    - goimports
    - revive
    - staticcheck
    - errcheck
    - copyloopvar
    - goconst
    - dupl
    - gocyclo
