FROM golang:1.24.0 as builder

WORKDIR /app
COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o grpc-burner cmd/grpc-burner/main.go

FROM alpine:3.20
WORKDIR /app
COPY --from=builder /app/grpc-burner /grpc-burner
ENTRYPOINT ["/grpc-burner"]
