apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  resource.customizations: |
    apiextensions.k8s.io/CustomResourceDefinition:
      ignoreDifferences: |
        jqPathExpressions:
        - .spec.conversion?.webhook?.clientConfig?.caBundle

        jsonPointers:
        - /metadata/annotations/kubectl.kubernetes.io~1last-applied-configuration

        managedFieldsManagers:
        - kube-controller-manager
        - kubectl-client-side-apply
