# This rule is not used by the project grpc-burner-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the grpc.burner.dev.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: grpc-burner-operator
    app.kubernetes.io/managed-by: kustomize
  name: observabilityconfig-editor-role
rules:
- apiGroups:
  - grpc.burner.dev
  resources:
  - observabilityconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - grpc.burner.dev
  resources:
  - observabilityconfigs/status
  verbs:
  - get
