apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otelcollector-k8sattributes
rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces", "nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["replicasets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: otelcollector-k8sattributes
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: otelcollector-k8sattributes
subjects:
  - kind: ServiceAccount
    name: otelcollector-opentelemetry-collector
    namespace: monitoring
