---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - grpc.burner.dev
  resources:
  - grpcburners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - grpc.burner.dev
  resources:
  - grpcburners/finalizers
  verbs:
  - update
- apiGroups:
  - grpc.burner.dev
  resources:
  - grpcburners/status
  verbs:
  - get
  - patch
  - update
