grafana:
  service:
    type: LoadBalancer
  persistence:
    enabled: false
    storageClassName: standard
    accessModes:
      - ReadWriteOnce
    size: 4Gi
  adminPassword: admin
  initChownData:
    enabled: false

prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: standard
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 8Gi

alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: standard
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 4Gi