apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-loki
  namespace: monitoring
  labels:
    grafana_datasource: "1"
data:
  loki-datasource.yaml: |-
    apiVersion: 1
    datasources:
      - name: Loki
        uid: loki
        type: loki
        access: proxy
        url: http://loki.monitoring.svc.cluster.local:3100
        isDefault: false
        jsonData:
          httpMethod: GET
          derivedFields:
            - name: trace_id
              matcherRegex: '"trace_id":"([a-f0-9-]+)"'
              datasourceUid: tempo
              url: ${__tempo_base_url}/trace/${__match_1}
            - name: traceId
              matcherRegex: '"traceId":"([a-f0-9-]+)"'
              datasourceUid: tempo
              url: ${__tempo_base_url}/trace/${__match_1}
