apiVersion: 1
datasources:
  - name: Tempo
    type: tempo
    access: proxy
    orgId: 1
    url: http://tempo.monitoring.svc.cluster.local:3100
    isDefault: false
    version: 1
    editable: true