apiVersion: grpc.burner.dev/v1alpha1
kind: GrpcBurner
metadata:
  name: sample-grpcburner
  namespace: default
spec:
  replicas: 1
  mode: unary
  messageSize: 512
  qps: 100
  duration: "5m"
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "200m"
      memory: "256Mi"