apiVersion: grpc.burner.dev/v1alpha1
kind: GrpcBurner
metadata:
  labels:
    app.kubernetes.io/name: grpc-burner-operator
    app.kubernetes.io/managed-by: kustomize
  name: grpcburner-sample
spec:
  # TODO(user): Add fields here
