apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grpc-portfolio
  namespace: argocd
spec:
  project: grpc-burner
  source:
    repoURL: https://github.com/shtsukada/grpc-burner-operator.git
    targetRevision: main
    path: deploy/argocd/apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true