// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/burner.proto

package burner

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BurnRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BurnRequest) Reset() {
	*x = BurnRequest{}
	mi := &file_proto_burner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BurnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BurnRequest) ProtoMessage() {}

func (x *BurnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_burner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BurnRequest.ProtoReflect.Descriptor instead.
func (*BurnRequest) Descriptor() ([]byte, []int) {
	return file_proto_burner_proto_rawDescGZIP(), []int{0}
}

type BurnResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BurnResponse) Reset() {
	*x = BurnResponse{}
	mi := &file_proto_burner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BurnResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BurnResponse) ProtoMessage() {}

func (x *BurnResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_burner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BurnResponse.ProtoReflect.Descriptor instead.
func (*BurnResponse) Descriptor() ([]byte, []int) {
	return file_proto_burner_proto_rawDescGZIP(), []int{1}
}

func (x *BurnResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_proto_burner_proto protoreflect.FileDescriptor

const file_proto_burner_proto_rawDesc = "" +
	"\n" +
	"\x12proto/burner.proto\x12\x06burner\"\r\n" +
	"\vBurnRequest\"(\n" +
	"\fBurnResponse\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload2B\n" +
	"\x06Burner\x128\n" +
	"\tUnaryBurn\x12\x13.burner.BurnRequest\x1a\x14.burner.BurnResponse\"\x00B\vZ\t./;burnerb\x06proto3"

var (
	file_proto_burner_proto_rawDescOnce sync.Once
	file_proto_burner_proto_rawDescData []byte
)

func file_proto_burner_proto_rawDescGZIP() []byte {
	file_proto_burner_proto_rawDescOnce.Do(func() {
		file_proto_burner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_burner_proto_rawDesc), len(file_proto_burner_proto_rawDesc)))
	})
	return file_proto_burner_proto_rawDescData
}

var file_proto_burner_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_burner_proto_goTypes = []any{
	(*BurnRequest)(nil),  // 0: burner.BurnRequest
	(*BurnResponse)(nil), // 1: burner.BurnResponse
}
var file_proto_burner_proto_depIdxs = []int32{
	0, // 0: burner.Burner.UnaryBurn:input_type -> burner.BurnRequest
	1, // 1: burner.Burner.UnaryBurn:output_type -> burner.BurnResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_burner_proto_init() }
func file_proto_burner_proto_init() {
	if File_proto_burner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_burner_proto_rawDesc), len(file_proto_burner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_burner_proto_goTypes,
		DependencyIndexes: file_proto_burner_proto_depIdxs,
		MessageInfos:      file_proto_burner_proto_msgTypes,
	}.Build()
	File_proto_burner_proto = out.File
	file_proto_burner_proto_goTypes = nil
	file_proto_burner_proto_depIdxs = nil
}
