// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: proto/burner.proto

package burner

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Burner_UnaryBurn_FullMethodName = "/burner.Burner/UnaryBurn"
)

// BurnerClient is the client API for Burner service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BurnerClient interface {
	UnaryBurn(ctx context.Context, in *BurnRequest, opts ...grpc.CallOption) (*BurnResponse, error)
}

type burnerClient struct {
	cc grpc.ClientConnInterface
}

func NewBurnerClient(cc grpc.ClientConnInterface) BurnerClient {
	return &burnerClient{cc}
}

func (c *burnerClient) UnaryBurn(ctx context.Context, in *BurnRequest, opts ...grpc.CallOption) (*BurnResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BurnResponse)
	err := c.cc.Invoke(ctx, Burner_UnaryBurn_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BurnerServer is the server API for Burner service.
// All implementations must embed UnimplementedBurnerServer
// for forward compatibility.
type BurnerServer interface {
	UnaryBurn(context.Context, *BurnRequest) (*BurnResponse, error)
	mustEmbedUnimplementedBurnerServer()
}

// UnimplementedBurnerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBurnerServer struct{}

func (UnimplementedBurnerServer) UnaryBurn(context.Context, *BurnRequest) (*BurnResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnaryBurn not implemented")
}
func (UnimplementedBurnerServer) mustEmbedUnimplementedBurnerServer() {}
func (UnimplementedBurnerServer) testEmbeddedByValue()                {}

// UnsafeBurnerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BurnerServer will
// result in compilation errors.
type UnsafeBurnerServer interface {
	mustEmbedUnimplementedBurnerServer()
}

func RegisterBurnerServer(s grpc.ServiceRegistrar, srv BurnerServer) {
	// If the following call pancis, it indicates UnimplementedBurnerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Burner_ServiceDesc, srv)
}

func _Burner_UnaryBurn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BurnRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BurnerServer).UnaryBurn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Burner_UnaryBurn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BurnerServer).UnaryBurn(ctx, req.(*BurnRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Burner_ServiceDesc is the grpc.ServiceDesc for Burner service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Burner_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "burner.Burner",
	HandlerType: (*BurnerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UnaryBurn",
			Handler:    _Burner_UnaryBurn_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/burner.proto",
}
