name: build
on:
  push:
    branches: [ main, "feature/**" ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 35

    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: Dockerfile
            tag_suffix: operator
          - dockerfile: Dockerfile.grpc-burner
            tag_suffix: grpc-burner

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Docker build (linux/amd64, no push)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64
          push: false
          tags: ghcr.io/${{ github.repository }}:${{ matrix.tag_suffix }}-ci-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max