name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Install Kubebuilder
        run: |
          KUBEBUILDER_VERSION=3.14.0
          OS=$(go env GOOS)
          ARCH=$(go env GOARCH)
          curl -L https://github.com/kubernetes-sigs/kubebuilder/releases/download/v${KUBEBUILDER_VERSION}/kubebuilder_${KUBEBUILDER_VERSION}_${OS}_${ARCH}.tar.gz \
            | tar -xz -C /tmp/
          sudo mv /tmp/kubebuilder_${KUBEBUILDER_VERSION}_${OS}_${ARCH} /usr/local/kubebuilder
      - name: Add Kubebuilder to PATH
        run: echo "/usr/local/kubebuilder/bin" >> $GITHUB_PATH

      - name: Verify manifests are up-to-date
        run: |
          make manifests
          git diff --exit-code

      - name: Run go vet
        run: make vet

      - name: Run unit tests
        run: make test
